// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto
// Protobuf Java Version: 4.33.4

package com.example.protosocket;

@com.google.protobuf.Generated
public final class Message extends com.google.protobuf.GeneratedFile {
  private Message() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "Message");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_protosocket_Packet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_protosocket_Packet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_protosocket_Packet_OptEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_protosocket_Packet_OptEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\027com.example.protosocket" +
      "\"\242\001\n\006Packet\022\014\n\004from\030\001 \001(\004\022\n\n\002to\030\002 \001(\004\022\r\n" +
      "\005flags\030\003 \001(\r\0225\n\003opt\030\004 \003(\0132(.com.example." +
      "protosocket.Packet.OptEntry\022\014\n\004data\030\005 \001(" +
      "\t\032*\n\010OptEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(" +
      "\t:\0028\001B\033\n\027com.example.protosocketP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_protosocket_Packet_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_com_example_protosocket_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_protosocket_Packet_descriptor,
        new java.lang.String[] { "From", "To", "Flags", "Opt", "Data", });
    internal_static_com_example_protosocket_Packet_OptEntry_descriptor =
      internal_static_com_example_protosocket_Packet_descriptor.getNestedType(0);
    internal_static_com_example_protosocket_Packet_OptEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_protosocket_Packet_OptEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
