// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto
// Protobuf Java Version: 4.33.4

package com.example.protosocket;

@com.google.protobuf.Generated
public interface PacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.protosocket.Packet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 from = 1;</code>
   * @return The from.
   */
  long getFrom();

  /**
   * <code>uint64 to = 2;</code>
   * @return The to.
   */
  long getTo();

  /**
   * <code>uint32 flags = 3;</code>
   * @return The flags.
   */
  int getFlags();

  /**
   * <code>map&lt;string, string&gt; opt = 4;</code>
   */
  int getOptCount();
  /**
   * <code>map&lt;string, string&gt; opt = 4;</code>
   */
  boolean containsOpt(
      java.lang.String key);
  /**
   * Use {@link #getOptMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getOpt();
  /**
   * <code>map&lt;string, string&gt; opt = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getOptMap();
  /**
   * <code>map&lt;string, string&gt; opt = 4;</code>
   */
  /* nullable */
java.lang.String getOptOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; opt = 4;</code>
   */
  java.lang.String getOptOrThrow(
      java.lang.String key);

  /**
   * <code>string data = 5;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 5;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
