// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto
// Protobuf Java Version: 4.33.4

package com.example.protosocket;

/**
 * Protobuf type {@code com.example.protosocket.Packet}
 */
@com.google.protobuf.Generated
public final class Packet extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.example.protosocket.Packet)
    PacketOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "Packet");
  }
  // Use Packet.newBuilder() to construct.
  private Packet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Packet() {
    data_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.protosocket.Message.internal_static_com_example_protosocket_Packet_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 4:
        return internalGetOpt();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.protosocket.Message.internal_static_com_example_protosocket_Packet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.protosocket.Packet.class, com.example.protosocket.Packet.Builder.class);
  }

  public static final int FROM_FIELD_NUMBER = 1;
  private long from_ = 0L;
  /**
   * <code>uint64 from = 1;</code>
   * @return The from.
   */
  @java.lang.Override
  public long getFrom() {
    return from_;
  }

  public static final int TO_FIELD_NUMBER = 2;
  private long to_ = 0L;
  /**
   * <code>uint64 to = 2;</code>
   * @return The to.
   */
  @java.lang.Override
  public long getTo() {
    return to_;
  }

  public static final int FLAGS_FIELD_NUMBER = 3;
  private int flags_ = 0;
  /**
   * <code>uint32 flags = 3;</code>
   * @return The flags.
   */
  @java.lang.Override
  public int getFlags() {
    return flags_;
  }

  public static final int OPT_FIELD_NUMBER = 4;
  private static final class OptDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.example.protosocket.Message.internal_static_com_example_protosocket_Packet_OptEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> opt_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetOpt() {
    if (opt_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          OptDefaultEntryHolder.defaultEntry);
    }
    return opt_;
  }
  public int getOptCount() {
    return internalGetOpt().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; opt = 4;</code>
   */
  @java.lang.Override
  public boolean containsOpt(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetOpt().getMap().containsKey(key);
  }
  /**
   * Use {@link #getOptMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getOpt() {
    return getOptMap();
  }
  /**
   * <code>map&lt;string, string&gt; opt = 4;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getOptMap() {
    return internalGetOpt().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; opt = 4;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getOptOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetOpt().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; opt = 4;</code>
   */
  @java.lang.Override
  public java.lang.String getOptOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetOpt().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int DATA_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object data_ = "";
  /**
   * <code>string data = 5;</code>
   * @return The data.
   */
  @java.lang.Override
  public java.lang.String getData() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      data_ = s;
      return s;
    }
  }
  /**
   * <code>string data = 5;</code>
   * @return The bytes for data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataBytes() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (from_ != 0L) {
      output.writeUInt64(1, from_);
    }
    if (to_ != 0L) {
      output.writeUInt64(2, to_);
    }
    if (flags_ != 0) {
      output.writeUInt32(3, flags_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetOpt(),
        OptDefaultEntryHolder.defaultEntry,
        4);
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, data_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (from_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, from_);
    }
    if (to_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, to_);
    }
    if (flags_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, flags_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetOpt().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      opt__ = OptDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, opt__);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, data_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.protosocket.Packet)) {
      return super.equals(obj);
    }
    com.example.protosocket.Packet other = (com.example.protosocket.Packet) obj;

    if (getFrom()
        != other.getFrom()) return false;
    if (getTo()
        != other.getTo()) return false;
    if (getFlags()
        != other.getFlags()) return false;
    if (!internalGetOpt().equals(
        other.internalGetOpt())) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FROM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFrom());
    hash = (37 * hash) + TO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTo());
    hash = (37 * hash) + FLAGS_FIELD_NUMBER;
    hash = (53 * hash) + getFlags();
    if (!internalGetOpt().getMap().isEmpty()) {
      hash = (37 * hash) + OPT_FIELD_NUMBER;
      hash = (53 * hash) + internalGetOpt().hashCode();
    }
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.protosocket.Packet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protosocket.Packet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protosocket.Packet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protosocket.Packet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protosocket.Packet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.protosocket.Packet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.protosocket.Packet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.protosocket.Packet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.protosocket.Packet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.protosocket.Packet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.protosocket.Packet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.protosocket.Packet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.protosocket.Packet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.protosocket.Packet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.protosocket.Packet)
      com.example.protosocket.PacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protosocket.Message.internal_static_com_example_protosocket_Packet_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 4:
          return internalGetOpt();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableOpt();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protosocket.Message.internal_static_com_example_protosocket_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protosocket.Packet.class, com.example.protosocket.Packet.Builder.class);
    }

    // Construct using com.example.protosocket.Packet.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      from_ = 0L;
      to_ = 0L;
      flags_ = 0;
      internalGetMutableOpt().clear();
      data_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.protosocket.Message.internal_static_com_example_protosocket_Packet_descriptor;
    }

    @java.lang.Override
    public com.example.protosocket.Packet getDefaultInstanceForType() {
      return com.example.protosocket.Packet.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.protosocket.Packet build() {
      com.example.protosocket.Packet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.protosocket.Packet buildPartial() {
      com.example.protosocket.Packet result = new com.example.protosocket.Packet(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.protosocket.Packet result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.from_ = from_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.to_ = to_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.flags_ = flags_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.opt_ = internalGetOpt();
        result.opt_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.data_ = data_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.protosocket.Packet) {
        return mergeFrom((com.example.protosocket.Packet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.protosocket.Packet other) {
      if (other == com.example.protosocket.Packet.getDefaultInstance()) return this;
      if (other.getFrom() != 0L) {
        setFrom(other.getFrom());
      }
      if (other.getTo() != 0L) {
        setTo(other.getTo());
      }
      if (other.getFlags() != 0) {
        setFlags(other.getFlags());
      }
      internalGetMutableOpt().mergeFrom(
          other.internalGetOpt());
      bitField0_ |= 0x00000008;
      if (!other.getData().isEmpty()) {
        data_ = other.data_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              from_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              to_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              flags_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              opt__ = input.readMessage(
                  OptDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableOpt().getMutableMap().put(
                  opt__.getKey(), opt__.getValue());
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              data_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long from_ ;
    /**
     * <code>uint64 from = 1;</code>
     * @return The from.
     */
    @java.lang.Override
    public long getFrom() {
      return from_;
    }
    /**
     * <code>uint64 from = 1;</code>
     * @param value The from to set.
     * @return This builder for chaining.
     */
    public Builder setFrom(long value) {

      from_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 from = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrom() {
      bitField0_ = (bitField0_ & ~0x00000001);
      from_ = 0L;
      onChanged();
      return this;
    }

    private long to_ ;
    /**
     * <code>uint64 to = 2;</code>
     * @return The to.
     */
    @java.lang.Override
    public long getTo() {
      return to_;
    }
    /**
     * <code>uint64 to = 2;</code>
     * @param value The to to set.
     * @return This builder for chaining.
     */
    public Builder setTo(long value) {

      to_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 to = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      to_ = 0L;
      onChanged();
      return this;
    }

    private int flags_ ;
    /**
     * <code>uint32 flags = 3;</code>
     * @return The flags.
     */
    @java.lang.Override
    public int getFlags() {
      return flags_;
    }
    /**
     * <code>uint32 flags = 3;</code>
     * @param value The flags to set.
     * @return This builder for chaining.
     */
    public Builder setFlags(int value) {

      flags_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 flags = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlags() {
      bitField0_ = (bitField0_ & ~0x00000004);
      flags_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> opt_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetOpt() {
      if (opt_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            OptDefaultEntryHolder.defaultEntry);
      }
      return opt_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableOpt() {
      if (opt_ == null) {
        opt_ = com.google.protobuf.MapField.newMapField(
            OptDefaultEntryHolder.defaultEntry);
      }
      if (!opt_.isMutable()) {
        opt_ = opt_.copy();
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return opt_;
    }
    public int getOptCount() {
      return internalGetOpt().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; opt = 4;</code>
     */
    @java.lang.Override
    public boolean containsOpt(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetOpt().getMap().containsKey(key);
    }
    /**
     * Use {@link #getOptMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getOpt() {
      return getOptMap();
    }
    /**
     * <code>map&lt;string, string&gt; opt = 4;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getOptMap() {
      return internalGetOpt().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; opt = 4;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getOptOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetOpt().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; opt = 4;</code>
     */
    @java.lang.Override
    public java.lang.String getOptOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetOpt().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearOpt() {
      bitField0_ = (bitField0_ & ~0x00000008);
      internalGetMutableOpt().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; opt = 4;</code>
     */
    public Builder removeOpt(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableOpt().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableOpt() {
      bitField0_ |= 0x00000008;
      return internalGetMutableOpt().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; opt = 4;</code>
     */
    public Builder putOpt(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableOpt().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; opt = 4;</code>
     */
    public Builder putAllOpt(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableOpt().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000008;
      return this;
    }

    private java.lang.Object data_ = "";
    /**
     * <code>string data = 5;</code>
     * @return The data.
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string data = 5;</code>
     * @return The bytes for data.
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string data = 5;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      data_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string data = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      data_ = getDefaultInstance().getData();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string data = 5;</code>
     * @param value The bytes for data to set.
     * @return This builder for chaining.
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      data_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.example.protosocket.Packet)
  }

  // @@protoc_insertion_point(class_scope:com.example.protosocket.Packet)
  private static final com.example.protosocket.Packet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.protosocket.Packet();
  }

  public static com.example.protosocket.Packet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Packet>
      PARSER = new com.google.protobuf.AbstractParser<Packet>() {
    @java.lang.Override
    public Packet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Packet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Packet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.protosocket.Packet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

